### ISSUE TITLE
Test installation at univ

### ISSUE THREAD

**Issue by calve** [calve/prof#4]
To target more users, we should check the installation procedure on school computers

Facts :

   - we are not root on it
   - python3 may not be installed

**Comment by WebTogz** [comment]
The real problem is to install the required modules like 'requests'... Do you think we can ask admins to install it? Or, we have to code our HTTP Python module... (:D)
I think (but i'm not sure) Python3 is installed on school computers - some students work PAC with those computers for example.

**Comment by calve** [comment]
I packaged prof to be installable using pip, which can install packages inside user home dir. So it could be a matter of getting pip on Debian.

Or we could make a virtualenv, providing all dependancies.

**Comment by WebTogz** [comment]
Personnaly, I prefer to make a virtualenv... But if you have allready make the PIP packaging, i'm ok :-)

**Comment by calve** [comment]
Did it just now

# Installation

``HTTP_PROXY=cache-etu.univ-lille1.fr:3128 pip-3.2 install --user prof``

# Execution

``~/.local/bin/prof``
